### ISSUE TITLE
Can this pass the UI thread for Handler

### ISSUE THREAD

**Issue by jzlhll** [jan4984/AndroidHandlerForDNet#1]
Can this pass the UI thread for Handler, cause sometimes want to refresh UI control.
Also, I'm quite known about Android Activity Thread, so It maybe cannot implement, because of threadLocal is not binding or loop not prepare before init. So how can I do UI work after handlerMssage .

**Comment by jan4984** [comment]
only if you can control the thread creation and UI events route.
